plugins {

}

dependencies {
    implementation project(':common')
    implementation project(':orders:orders-api')
    implementation project(':orders:orders-domain')

    implementation project(':members:members-api')
    implementation project(':products:products-api')

    implementation 'org.springframework.boot:spring-boot-starter'
}
