plugins {

}

dependencies {
    implementation project(':gateway')

    implementation 'org.springframework.boot:spring-boot-starter'

    // Lombok (로그용, 필드 자동 주입용 등)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform() // JUnit5 사용
}