rootProject.name = 'modular-study'

include(
        'app',
        'common',

        'members:members-api',
        'members:members-domain',
        'members:members-service',
        'members:members-infrastructure',

        'orders:orders-api',
        'orders:orders-domain',
        'orders:orders-service',
        'orders:orders-infrastructure',

        'products:products-api',
        'products:products-domain',
        'products:products-service',
        'products:products-infrastructure',
)