plugins {

}

dependencies {
    implementation project(':orders:orders-api')
    implementation project(':orders:orders-domain')
    implementation project(':orders:orders-service')

    implementation project(':members:members-api')
    implementation project(':members:members-domain')
    implementation project(':members:members-service')

    implementation project(':products:products-api')
    implementation project(':products:products-domain')
    implementation project(':products:products-service')


    implementation 'org.springframework.boot:spring-boot-starter'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform() // JUnit5 사용
}